### PR TITLE
Update actions for bor release

### PR DESCRIPTION
**Pull request by Santonclause**
# Description

New release Actions update.

Actions will be triggered manually. The workflow will:

- check if there is a new version of release in the upstream
- if yes, fetch new tags, checkout to the new tag and apply the patch
- build new binaries and publish in the repo
- build new docker image for the new tag and publish into docker hub

### CODE REVIEW

**Comment by Santonclause** [comment]
hey @jj1980a , can you please review? We can test it manually when a new release published in the upstream.

**Review by jj1980a — APPROVED** [review]
lgtm!

**Comment by ephess** [comment]
My only concern is that by re-using the upstream .gihub files, we may end up with merge conflicts or issues when rebasing. Should we perhaps do this instead using a new file, and disable the upstream files somehow that is less likely to result in conflicts?

Low conviction feedback.

**Comment by Santonclause** [comment]
> My only concern is that by re-using the upstream .gihub files, we may end up with merge conflicts or issues when rebasing. Should we perhaps do this instead using a new file, and disable the upstream files somehow that is less likely to result in conflicts?
> 
> Low conviction feedback.

@ephess thank you, valid concerns. I've put the original file back and added our actions as a manual trigger.

**Pull request merged**
